name: Bug
description: Something doesn't work
title: "bug: "
labels: ["type:bug"]
body:
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations: { required: true }
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations: { required: true }
  - type: textarea
    id: repro
    attributes:
      label: Repro steps
      placeholder: "1. …\n2. …"
